### ISSUE TITLE
Debug Flow

### ISSUE THREAD

**Issue by msdogan** [msdogan/HOBBEStoPRMcomparison#1]
I was able to run a test CALVIN run (debug mode) generated with following commands:
`prm build --prefix test_dbg --debug All` This command generates three input files: test_dbg.pri, test_dbgTS.dss and test_dbgPD.dss
`prm run --prefix test_dbg` This command runs HEC-PRM and generates output files: test_dbg.pro and test_dbg.dss

**Following updates are made to test_dbg.pri file before running the model.**
![capture](https://cloud.githubusercontent.com/assets/14085662/16536102/91d79334-3fa2-11e6-819f-b662fe2d455a.JPG)
First three updates are not crucial (SR_CR1,2.3), however, without other updates, HEC-PRM terminates immediately after checking the network.

**Following changes are made to penalty data (test_dbgPD.dss)**
- Penalty data for link HXI101-EXT_REDDIN and HXI201-EXT_YUBA for FEB are updated.
- The figure and table on the top are from test_dbgPD.dss generated above command, and the figure and table below are updated based on previous CALVIN run.
  ![capture](https://cloud.githubusercontent.com/assets/14085662/16536206/c4b25716-3fa3-11e6-9f82-4a2dd38ff6a1.JPG)

After running the test.dbg model run, flow finder macro is run to look at debug flows. 
- There is total of 0.292240903 TAF of debug flow in the system. This is overall sum over 82 years. There is only one location with debug flows: DBUGSRC-SR_GNT
  There is a minimum in-stream flow (MIF) requirement on SR_GNT-SR-ML. Following figure shows marginal value on MIF and debug flow amounts, which perfectly match.

![debug](https://cloud.githubusercontent.com/assets/14085662/16536323/f245fb96-3fa4-11e6-949c-51de8279d95e.jpg)

So, in order to get a feasible solution, the next step would be to reduce MIF by debug flow amount, which is a quite flow small, but it is big enough to create infeasibilities.

**Comment by qjhart** [comment]
The reason for the missing BL link in the sink is due to the recursive nature of the writeLink() function in the file calvin-network-tools/nodejs/pri/format/link.js.  In the ```if (np.sinks)``` function, if a sink is found, it calls a new writeLink() function.  However, the CSV links are not dereferenced.  As a result, the bounds are not filled out, and a BL line is not created.  Example: /data/south-lahontan/mono-owens-area/sr_ol/node.geojson

**Comment by qjhart** [comment]
Mustafa, I wanted to then assign jrmerz to that task, but I don;t have priviledges to do that.

**Comment by msdogan** [comment]
debug flows were due to roundoff errors in pri file.
