### ISSUE TITLE
Constrained flows

### ISSUE THREAD

**Issue by msdogan** [msdogan/HOBBEStoPRMcomparison#2]
Quinn,

It came to my attention that constrained flows are not represented in *.pri files. If you can take a look at S09I05.pri, constrained flows have QC in the first column. I have zipped S09I05.pri and test_dbg.pri
Here is a few examples: C150-SINK, C20-D55, C7-C20. Those have constrained flows in S09I05 but not in test_dbg. These constrained flows have time-series data stored in S09I05TS.DSS

[pri_files.zip](https://github.com/msdogan/HOBBEStoPRMcomparison/files/344285/pri_files.zip)

**Comment by msdogan** [comment]
@jrmerz @qjhart I am reopening this issue for calibration flows, which are also constrained. CN2-C35 and CN2-N201. I previously added them (long before run S09I05) because I could not eliminate debug flows for these two nodes and ended up adding calibration flows.

**Comment by qjhart** [comment]
@msdogan CN2-N201 is in there, (QC file). However, CN2-C35 is missing completely from the database,   I'll see why that is.

**Comment by msdogan** [comment]
@qjhart please ignore what I said for C35. We are in good shape. CN2-N201 is in database. Sorry for confusion. Thanks.

**Comment by qjhart** [comment]
According to @msdogan this is not a problem.
