### ISSUE TITLE
compare pumping operations

### ISSUE THREAD

**Issue by msdogan** [msdogan/HOBBEStoPRMcomparison#8]
Compare pumping prices both in input and output files, along with operations (output).

**Comment by msdogan** [comment]
@whiteellie since you know pumps and their penalties much better than me, can I assign this issue to you?
path to test run's input and outputs files: `X:\calvin\HOBBES`

**Comment by whiteellie** [comment]
Sure @msdogan.

**Comment by jdherman** [comment]
Thanks to @qjhart 

Here's an example showing the biggest RMS  differences between S09I05 (s) and Hobbes test (h) where rmse = sqrt( sum ( (s-h)^2 ) ) over all the years.  You can see flows that run along certain sets of links,

```
      prmname      |  s_val  |  h_val  | rmse  
-------------------+---------+---------+-------
 D800-D801         |  322544 |  333292 | 10748
 D801-D803         |  322412 |  333157 | 10745
 D804-D814         |  321712 |  332446 | 10734
 D803-D804         |  322343 |  333078 | 10734
 PMP_Banks-D800    |  320329 |  329866 |  9537
 D59-PMP_Banks     |  320329 |  329866 |  9537
 D710-PMP_ONeill   |   43086 |   33920 |  9167
 PMP_ONeill-D814   |   43086 |   33920 |  9167
 D507-D509         |  956941 |  947783 |  9158
 D511-D55          |  838528 |  830324 |  8205
 D55-D507          |  979218 |  971016 |  8202
 D523-D525         |  769172 |  777141 |  7969
 D701-D700         |  237729 |  230190 |  7539
 D700-D703         |  237729 |  230190 |  7539
 D703-D710         |  236213 |  228674 |  7539
 D522-D523         |  806876 |  813972 |  7096
 D511-D513         |  510925 |  517994 |  7069
 D515-D522         |  519560 |  526367 |  6807
 D513-D515         |  478750 |  485118 |  6368
 PMP_Tracy-D701    |  239945 |  233616 |  6329
 D59-PMP_Tracy     |  239945 |  233616 |  6329
 D528-D509         |  193728 |  198488 |  4760
 D525-D528         |  193985 |  198746 |  4760
 D541-Surp_Delta   |  754073 |  749675 |  4398
 D509-D541         | 1163563 | 1159165 |  4398
 D814-PMP_Gianel   |   66740 |   70765 |  4026
 PMP_Gianel-SR_SNL |   66740 |   70765 |  4026
 SR_SNL-PWP_Gianel |   38162 |   42051 |  3889
 PWP_Gianel-D816   |   38162 |   42051 |  3889
 D608-HSU404AD60   |   57459 |   61165 |  3706
 D752-D855         |  155234 |  158897 |  3663
 C95-D752          |  194791 |  198328 |  3537
 D853-C95          |  194791 |  198328 |  3537
 D850-D851         |  146919 |  150456 |  3537
 D851-D853         |  195767 |  199304 |  3537
 D845-D850         |  226084 |  229606 |  3522
 C75-D845          |  243506 |  247028 |  3522
 D887-SR_CAS       |   64830 |   68292 |  3462
 D886-PWP_Castai   |   65026 |   68489 |  3462
 SR_PYM-D886       |   65281 |   68743 |  3462
 PWP_Castai-D887   |   65026 |   68489 |  3462
```

**Comment by msdogan** [comment]
Here are my findings for pumping operations:
test pumped about 3 taf/m (36 taf/y) more than S09I05 from the Delta. Through, California Aqueduct, almost all of water sent to thirsty LA (MWD), reducing urban water scarcity in that region. Excess water comes from Sacramento River through Delta Cross Channel (DCC). Test run diverted about 8 taf/m more Sac River through DCC and only 3 taf/m sent to pumps, the rest went to delta outflow.
For the Sac River, flows are almost the same at Hood in both runs: 1371 taf/m in S09I05, and 1370.24 in test. So, in S09I05, there is less water in Rio Vista (about 8 taf/m).

I still couldn't find why S09I05 couldn't send more water through DCC to reduce scarcities in the south. There may be some capacity constraints I think hindering this. But, problem is on Delta operations.

![capture](https://cloud.githubusercontent.com/assets/14085662/18523445/20e7782c-7a69-11e6-9a08-aa397a17e2d6.JPG)

**Comment by whiteellie** [comment]
Here are my comparisons (these were done in R, I am more confident in these numbers than the ones I showed on Friday): 
![image](https://cloud.githubusercontent.com/assets/18252415/18526560/db27839c-7a75-11e6-982c-5f0346696e51.png)

**Comment by jdherman** [comment]
Thanks @msdogan and @whiteellie ! So if I'm understanding this ...
- The net mass balance between `test` and `S09I05` seems to match pretty well
- But there are internal differences in flows through the delta
- From Quinn's list, it looks like DCC is the furthest-upstream link with large differences. Maybe all of the others follow from this one?
- Like Mustafa suggested, is it possible to compare the constraints on DCC? And maybe the cost curves on the pumping plants.

**Comment by msdogan** [comment]
@jdherman for my comparison for Delta operations, the biggest problem is poor representation of Delta water operations (Jay always says other models does not have a good representation of Delta, either) because operations are not linear at all. For example, Delta Cross Channel has a capacity of 3500 cfs, which is about 200 TAF/m, but if you look at monthly average flows in CALVIN on DCC, it is about 520 TAF/m. Aside from that overall mass balance looks fine for my comparison. Extra water is coming from Delta outflow. So, in test run, more water is exported from Delta and there is less Delta outflow. I think this is also consistent with Ellie's findings.

**Comment by jdherman** [comment]
Ok but regardless of whether it's a good representation of reality, we still want them to be the same :)   (even if they are equally bad representations).

How can the monthly average DCC flows exceed the constraint value?

**Comment by msdogan** [comment]
Yes, that's true. It is not a justification for flow difference between runs. The DCC upper bound is applied on link D513-D521. However, there are links D511-D513-D515-D522 acting like shortcut. Maybe we should update it. Right now, upper bound does not do its job.

**Comment by whiteellie** [comment]
I checked the cost curves on the pumps and they are not very big differences (looks like rounding to me)... 
row 21 is the average difference, 22 the min, and 23 the max. 

Banks
![captureb](https://cloud.githubusercontent.com/assets/18252415/18533129/ad741b3e-7a95-11e6-857e-babda432048c.PNG)
Gianelli
![captureg](https://cloud.githubusercontent.com/assets/18252415/18533134/b1746680-7a95-11e6-99a9-4ef6f58d5002.PNG)
Tracy
![capturet](https://cloud.githubusercontent.com/assets/18252415/18533135/b3384860-7a95-11e6-9895-ce6e0f429ae5.PNG)

**Comment by whiteellie** [comment]
@msdogan do the upper and lower bounds get written in the pri file? I couldn't find them, If they are coming from access database then there's no way they can be different.

**Comment by msdogan** [comment]
@whiteellie if it is constant or monthly varying upper or lower bound, it is stored in `pri`. If time-varying (time-series), it is stored in `dss`

**Comment by jdherman** [comment]
Ok it does look like the costs are just rounding differences, so that's probably not the issue. Thanks Ellie. 

Mustafa's point about the "shortcut" around the DCC is interesting. That's one place where there are big differences between test and S09I05 according to Quinn's list.

This is weird, and I'm very confused. Is it possible that in S09I05 the *pri file was changed manually, after exporting it from netbuilder? Or was it re-generated for these runs?

**Comment by msdogan** [comment]
@jdherman I don't remember modifying the `*pri` file. S09I05 was the latest historical run without debug flows after a few updates (cost curves for pumping plants and link labels) last year. It wasn't specifically for HOBBES.

**Comment by jdherman** [comment]
Alright thanks. And I saw those updates were also included in the HOBBES data last year. So there shouldn't be any differences.

Well, this continues to be a mystery.

**Comment by msdogan** [comment]
Yes, there shouldn't be any data differences because HOBBES gets data from S09I05. But, something might have happened while reading the data or printing to *pri from HOBBES.

**Comment by jrmerz** [comment]
@msdogan @qjhart @jdherman

[PriDiffNoRounding.txt](https://github.com/msdogan/HOBBEStoPRMcomparison/files/478440/PriDiffNoRounding.txt)
[PriDiffRounding1dp.txt](https://github.com/msdogan/HOBBEStoPRMcomparison/files/478441/PriDiffRounding1dp.txt)

All,  I have a first pass and parsing and comparing PRI files from S09I05 and HOBBES.  There are two different version.  One has no rounding, you will see there are 83 nodes/links with values that do not match.  The other rounds to 1 decimal place, then compares; it has 7 nodes/links that are different.  At the top of the file are a list of nodes/links that only exist in one file.  Currently this list shows the couple CN\* nodes that are in S09I05 and not HOBBES.

At the moment I am not comparing every value from the PRI file, only the first line information, so things like BU are not compared.  Here is a list of what is compared.

var node = ['initialStorage', 'areaCapfactor', 'endingStorage'];
var link = ['amplitude', 'cost', 'lowerBound', 'upperBound', 'constantBound'];

Let me know if further analysis like this would be helpful.

**Comment by whiteellie** [comment]
Thanks @jrmerz. Those look similar to me. @msdogan Do you think the CN nodes could be the problem? we can try running calvin S09I05 again without the calibration nodes. Then the outputs should match exactly (unless it's a multiple optima issue).

**Comment by jdherman** [comment]
Thanks Justin, this is really helpful. I guess there are two options here. Either:
(1) The accumulation of all PRI rounding is causing the differences, or
(2) The PRI rounding is irrelevant, and there are some other big differences buried in the two DSS files

So then two questions I feel bad even asking:
- Since you already have a PRI parser, is it possible to modify it to read `test.pri` and in the process also write out `test_rounded.pri`? This was Mimi's suggestion on Friday: to try to eliminate the rounding differences and re-run the `test` optimization, compare outputs.
- Or, if we believe (2) instead, is it possible to do a similar comparison of the TS/PD DSS input files for the `test` and `S09I05` cases? I'm wondering in particular if the inflow time series are being rounded. (If there is a monthly rounding difference of 0.01 TAF on a single link, that adds up to ~10 TAF over the full time period .... multiply by the number of links, I think it could matter.)

On Tuesday we can talk about which (if either) of these things are worth pursuing. I'll send an email tomorrow and try to figure out hangouts for Justin if you can make it. Thanks!

**Comment by msdogan** [comment]
@jrmerz thanks for the list. @jdherman I think it is good idea to create a new `test` run with rounded values in the `pri`. So, based on the pri comparison that I did in June (HOBESS_PRI_to_HECPRM_PRI_Comparison.doc [HOBESS_PRI_to_HECPRM_PRI_Comparison.zip](https://github.com/msdogan/HOBBEStoPRMcomparison/files/479090/HOBESS_PRI_to_HECPRM_PRI_Comparison.zip)), I introduced rounding using S09I05 as guide. So, number are rounded according to `S09I05.pri`. The list I used covers @jrmerz 's list, as well. I will let you all know with results once new test run with S09I05 rounding ends. Here are numbers that I changed (rounded):
**old `test` run without rounding ([test_rounded_differently.txt](https://github.com/msdogan/HOBBEStoPRMcomparison/files/479104/test_rounded_differently.txt)):**

```
*********************NODES*****************************************
Type      Node_ID        Initial  Evap_Coef  Ending

NODE      SR_BVLB        0.001    0.0000
NODE      SR_CR1         0.010    0.0000     0.010
NODE      SR_CR2         0.010    0.0000     0.010
NODE      SR_CR3         0.010    0.0000     0.000
NODE      SR_ML       2939.541    0.0140
NODE      SR_OL          0.010    0.0000
NODE      SR_RLL_CMB    48.669    0.0102    48.669
NODE      SR_TL          0.001    0.0000
NODE      SR_BER       806.300    0.0097   806.300
NODE      SR_BLB        80.200    0.0185    80.200
NODE      SR_BUC        58.000    0.0087    39.040
NODE      SR_BUL       600.000    0.0051   600.000
NODE      SR_CFW        35.000    0.0026    35.000
NODE      SR_CLE      2053.000    0.0061  1774.070
NODE      SR_CLK_INV   306.700    0.0326   306.700
NODE      SR_CMN       200.000    0.0056   235.000
NODE      SR_CRW        92.500    0.0243    92.500
NODE      SR_DLV        28.000    0.0122    24.630
NODE      SR_DMV       600.000    0.0051   600.000
NODE      SR_DNP       373.000    0.0058  1695.130
NODE      SR_EBMUD     117.900    0.0107   117.900
NODE      SR_ENG        66.000    0.0102    66.000
NODE      SR_FOL       549.000    0.0112   649.750
NODE      SR_GNT        26.000    0.0225    26.000
NODE      SR_HID        24.000    0.0134    39.120
NODE      SR_HTH       330.600    0.0054   330.600
NODE      SR_ISB       281.900    0.0114   281.900
NODE      SR_LA         52.000    0.0316    52.000
NODE      SR_LL_ENR    216.600    0.0082   216.600
NODE      SR_LVQ        88.300    0.0101    88.300
NODE      SR_MCR       229.000    0.0064   834.590
NODE      SR_MHW       100.100    0.0175   100.100
NODE      SR_MIL       176.000    0.0088   213.150
NODE      SR_NHG       159.000    0.0112    92.000
NODE      SR_NML      1000.000    0.0046   792.560
NODE      SR_ORO      2555.000    0.0041  2633.350
NODE      SR_PAR       195.000    0.0073   203.000
NODE      SR_PNF       550.000    0.0038   550.000
NODE      SR_PRR       108.000    0.0183   108.380
NODE      SR_PYM       170.000    0.0072   143.940
NODE      SR_SCAGG      94.000    0.0204    94.000
NODE      SR_SCC        41.900    0.0224    41.900
NODE      SR_SFAGG     128.000    0.0191   128.000
NODE      SR_SHA      2496.000    0.0065  3699.320
NODE      SR_SKN        33.800    0.0279    33.800
NODE      SR_SLW        50.000    0.0056    45.640
NODE      SR_TAB        49.400    0.0700    10.890
NODE      SR_TRM        77.100    0.0059    77.100
NODE      SR_TUL        65.000    0.0192    65.000
NODE      SR_WHI       200.000    0.0125   235.000

*********************LINKS*****************************************
Type      Link_Type Origin    Terminal  Ampl      Cost       Lower_B  Upper_B

LINK      DIVR      C145      HARCH     1.0000    12.4764
LINK      DIVR      C158      HARCH     1.0000    1.6724
LINK      DIVR      D616      C42       1.0000    -0.0296
LINK      DIVR      D700      C30       1.0000    31.9680
LINK      DIVR      D744      C92       1.0000    -0.2960
LINK      DIVR      D801      PMP_SoBay 1.0000    33.1668
LINK      DIVR      D865      PMP_OSO   1.0000    462.6036
LINK      DIVR      HGP19     D851      1.0000    101.8240            53.0000
LINK      DIVR      PMP_Eagle PMP_JH    1.0000    10.4784
LINK      DIVR      PMP_Iron  PMP_Eagle 1.0000    10.4784
LINK      DIVR      PMP_JH    C136      1.0000    10.4784
LINK      DIVR      PMP_LosVaqSR_LVQ    1.0000    37.9620
LINK      DIVR      PMP_Old_R C310      1.0000    37.9620
LINK      DIVR      PMP_Wads  N5        1.0000    31.3020
LINK      DIVR      PMP_Wads  C138      1.0000    13.9860
LINK      DIVR      PMP_Wads  SR_DMV    1.0000    31.3020
LINK      DIVR      SR_WHI    D73       1.0000    0.0148
LINK      RSTO      SR_ISB    SR_ISB    1.000               0.1840
LINK      RSTO      SR_PNF    SR_PNF    1.000               45.3790
LINK      RSTO      SR_SCC    SR_SCC    1.000               0.5570
LINK      RSTO      SR_TRM    SR_TRM    1.000               0.5700
LINK      DIVR      C1        HSU102C1  1.0000                        1.9800
LINK      DIVR      C11       HSU102C11 1.0000                        1.0300
LINK      DIVR      C153      C156      1.0000                        67.6368
LINK      DIVR      D649      HSU306D6491.0000                        4.7300
LINK      DIVR      D694      HSU306D6941.0000                        0.5500
LINK      DIVR      D699      HSU305D6991.0000                        4.9500
LINK      DIVR      HGP21     C98       1.0000                        27.2500
LINK      DIVR      SR_CAS    C106      1.0000                        2.4156
LINK      DIVR      SR_PYM    C106      1.0000                        0.2625
LINK      DIVR      HGP01     A101      1.0000    39.4100             7.2100
LINK      DIVR      HGP02     A102      1.0000    43.5200             93.2300
LINK      DIVR      HGP03     A103B     1.0000    79.9700             175.7900
LINK      DIVR      HGP03     A103A     1.0000    57.1300             175.7900
LINK      DIVR      HGP04     A104      1.0000    39.1800             109.1700
LINK      DIVR      HGP05     A202      1.0000    40.0900             240.1400
LINK      DIVR      HGP05     R201      1.0000    40.0900             1.9500
LINK      DIVR      HGP05     R202      1.0000    40.0900             3.3600
LINK      DIVR      HGP06     U205      1.0000    74.0000             0.1133
LINK      DIVR      HGP08     A207      1.0000    74.7100             185.6200
LINK      DIVR      HGP10     R302      1.0000    62.9400             0.3700
LINK      DIVR      HGP10     A303      1.0000    62.9400             185.1500
LINK      DIVR      HGP11     A302      1.0000    61.0000             64.9500
LINK      DIVR      HGP12     A305      1.0000    59.4000             86.8500
LINK      DIVR      HGP13     A306      1.0000    61.9100             225.7700
LINK      DIVR      HGP13     R301      1.0000    61.9100             2.0100
LINK      DIVR      HGP14     A402B     1.0000    176.9900            221.1300
LINK      DIVR      HGP14     A402A     1.0000    176.9900            221.1300
LINK      DIVR      HGP15     A404B     1.0000    74.3700             335.2500
LINK      DIVR      HGP15     A404A     1.0000    74.3700             335.2500
LINK      DIVR      HGP16     A401      1.0000    62.3700             61.7700
LINK      DIVR      HGP17     A403      1.0000    55.2800             152.6200
LINK      DIVR      HGP19     A408B     1.0000    136.2000            213.6900
LINK      DIVR      HGP19     A408A     1.0000    136.2000            213.6900
LINK      DIVR      HGP20     A407      1.0000    142.1400            125.2800
LINK      DIVR      HGP21     A409C     1.0000    119.5100            265.6500
LINK      DIVR      HGP21     A409B     1.0000    119.5100            265.6500
LINK      DIVR      HGP21     A409A     1.0000    119.5100            265.6500
LINK      DIVR      HGPSBV    U506      1.0000    51.8000             23.1100
LINK      DIVR      U506      HARSBV    1.0000    7.4000              28.6600
LINK      DIVR      WWP201    HNP201    1.0000    1480.0000           1.8600
LINK      DIVR      WWP204    HNP204    1.0000    518.0000            0.5600
LINK      DIVR      WWP205    HNP205    1.0000    1480.0000           2.9300
LINK      DIVR      WWP207    HNP207    1.0000    1480.0000           1.8700
LINK      DIVR      WWP209    HNP209    1.0000    518.0000            2.1200
LINK      DIVR      WWP210    HNP210    1.0000    1480.0000           2.4800
LINK      DIVR      WWP301    HNP301    1.0000    1480.0000           3.6500
LINK      DIVR      WWP302    HNP302    1.0000    1480.0000           5.2900
LINK      DIVR      WWP304    HNP304    1.0000    518.0000            1.3300
LINK      DIVR      WWP401    HNP401    1.0000    1480.0000           8.1100
LINK      DIVR      WWP403    HNP403    1.0000    1480.0000           3.3400
LINK      DIVR      WWP405    HNP405    1.0000    1480.0000           4.7900
LINK      DIVR      WWP406    HNP406    1.0000    1480.0000           3.8500
LINK      DIVR      WWP407    HNP407    1.0000    1480.0000           3.1800
LINK      DIVR      WWP410    HNP410    1.0000    1480.0000           6.0600
LINK      DIVR      WWP501    HNP501    1.0000    518.0000            0.0200
LINK      DIVR      WWP504    HNP504    1.0000    1258.0000           28.7200
LINK      DIVR      WWP508    HNP508    1.0000    1480.0000           0.9190
LINK      DIVR      WWP510    HNP510    1.0000    1480.0000           1.0400
```

**`S09I05.pri` rounding ([S09I05_rounded_differently.txt](https://github.com/msdogan/HOBBEStoPRMcomparison/files/479106/S09I05_rounded_differently.txt)):**

```
*********************NODES*****************************************
Type      Node_ID   Initial   Evap_Coef Ending

NODE      SR_BVLB   0.0       0.000
NODE      SR_CR1    0.0       0.000     0.0
NODE      SR_CR2    0.0       0.000     0.0
NODE      SR_CR3    0.0       0.000     0.0
NODE      SR_ML     2939.5    0.014
NODE      SR_OL     0.0       0.000
NODE      SR_RLL_CMB48.7      0.010     48.7
NODE      SR_TL     0.0       0.000
NODE      SR_BER    806.3     0.010     806.3
NODE      SR_BLB    80.2      0.019     80.2
NODE      SR_BUC    58.0      0.009     39.0
NODE      SR_BUL    600.0     0.005     600.0
NODE      SR_CFW    35.0      0.003     35.0
NODE      SR_CLE    2053.0    0.006     1774.1
NODE      SR_CLK_INV306.7     0.033     306.7
NODE      SR_CMN    200.0     0.006     235.0
NODE      SR_CRW    92.5      0.024     92.5
NODE      SR_DLV    28.0      0.012     24.6
NODE      SR_DMV    600.0     0.005     600.0
NODE      SR_DNP    373.0     0.006     1695.1
NODE      SR_EBMUD  117.9     0.011     117.9
NODE      SR_ENG    66.0      0.010     66.0
NODE      SR_FOL    549.0     0.011     649.8
NODE      SR_GNT    26.0      0.022     26.0
NODE      SR_HID    24.0      0.013     39.1
NODE      SR_HTH    330.6     0.005     330.6
NODE      SR_ISB    281.9     0.011     281.9
NODE      SR_LA     52.0      0.032     52.0
NODE      SR_LL_ENR 216.6     0.008     216.6
NODE      SR_LVQ    88.3      0.010     88.3
NODE      SR_MCR    229.0     0.006     834.6
NODE      SR_MHW    100.1     0.018     100.1
NODE      SR_MIL    176.0     0.009     213.2
NODE      SR_NHG    159.0     0.011     92.0
NODE      SR_NML    1000.0    0.005     792.6
NODE      SR_ORO    2555.0    0.004     2633.4
NODE      SR_PAR    195.0     0.007     203.0
NODE      SR_PNF    550.0     0.004     550.0
NODE      SR_PRR    108.0     0.018     108.4
NODE      SR_PYM    170.0     0.007     143.9
NODE      SR_SCAGG  94.0      0.020     94.0
NODE      SR_SCC    41.9      0.022     41.9
NODE      SR_SFAGG  128.0     0.019     128.0
NODE      SR_SHA    2496.0    0.006     3699.3
NODE      SR_SKN    33.8      0.028     33.8
NODE      SR_SLW    50.0      0.006     45.6
NODE      SR_TAB    49.4      0.070     10.9
NODE      SR_TRM    77.1      0.006     77.1
NODE      SR_TUL    65.0      0.019     65.0
NODE      SR_WHI    200.0     0.012     235.0

*********************LINKS*****************************************
Type      Link_Type Origin    Terminal  Ampl      Cost       Lower_B  Upper_B

LINK      DIVR      C145      HARCH     1.000     12.48
LINK      DIVR      C158      HARCH     1.000     1.67
LINK      DIVR      D616      C42       1.000     -0.03
LINK      DIVR      D700      C30       1.000     31.97
LINK      DIVR      D744      C92       1.000     -0.30
LINK      DIVR      D801      PMP_SOBAY 1.000     33.17
LINK      DIVR      D865      PMP_OSO   1.000     462.60
LINK      DIVR      HGP19     D851      1.000     101.82              53.0
LINK      DIVR      PMP_EAGLE PMP_JH    1.000     10.48
LINK      DIVR      PMP_IRON  PMP_EAGLE 1.000     10.48
LINK      DIVR      PMP_JH    C136      1.000     10.48
LINK      DIVR      PMP_LOSVAQSR_LVQ    1.000     37.96
LINK      DIVR      PMP_OLD_R C310      1.000     37.96
LINK      DIVR      PMP_WADS  N5        1.000     31.30
LINK      DIVR      PMP_WADS  C138      1.000     13.99
LINK      DIVR      PMP_WADS  SR_DMV    1.000     31.30
LINK      DIVR      SR_WHI    D73       1.000     0.01
LINK      RSTO      SR_ISB    SR_ISB    1.000               0.2
LINK      RSTO      SR_PNF    SR_PNF    1.000               45.4
LINK      RSTO      SR_SCC    SR_SCC    1.000               0.6
LINK      RSTO      SR_TRM    SR_TRM    1.000               0.6
LINK      DIVR      C1        HSU102C1  1.000                         2.0
LINK      DIVR      C11       HSU102C11 1.000                         1.0
LINK      DIVR      C153      C156      1.000                         67.6
LINK      DIVR      D649      HSU306D6491.000                         4.7
LINK      DIVR      D694      HSU306D6941.000                         0.6
LINK      DIVR      D699      HSU305D6991.000                         5.0
LINK      DIVR      HGP21     C98       1.000                         27.3
LINK      DIVR      SR_CAS    C106      1.000                         2.4
LINK      DIVR      SR_PYM    C106      1.000                         0.3
LINK      DIVR      HGP01     A101      1.000     39.41               7.2
LINK      DIVR      HGP02     A102      1.000     43.52               93.2
LINK      DIVR      HGP03     A103B     1.000     79.97               175.8
LINK      DIVR      HGP03     A103A     1.000     57.13               175.8
LINK      DIVR      HGP04     A104      1.000     39.18               109.2
LINK      DIVR      HGP05     A202      1.000     40.09               240.1
LINK      DIVR      HGP05     R201      1.000     40.09               2.0
LINK      DIVR      HGP05     R202      1.000     40.09               3.4
LINK      DIVR      HGP06     U205      1.000     74.00               0.1
LINK      DIVR      HGP08     A207      1.000     74.71               185.6
LINK      DIVR      HGP10     R302      1.000     62.94               0.4
LINK      DIVR      HGP10     A303      1.000     62.94               185.2
LINK      DIVR      HGP11     A302      1.000     61.00               65.0
LINK      DIVR      HGP12     A305      1.000     59.40               86.9
LINK      DIVR      HGP13     A306      1.000     61.91               225.8
LINK      DIVR      HGP13     R301      1.000     61.91               2.0
LINK      DIVR      HGP14     A402B     1.000     176.99              221.1
LINK      DIVR      HGP14     A402A     1.000     176.99              221.1
LINK      DIVR      HGP15     A404B     1.000     74.37               335.3
LINK      DIVR      HGP15     A404A     1.000     74.37               335.3
LINK      DIVR      HGP16     A401      1.000     62.37               61.8
LINK      DIVR      HGP17     A403      1.000     55.28               152.6
LINK      DIVR      HGP19     A408B     1.000     136.20              213.7
LINK      DIVR      HGP19     A408A     1.000     136.20              213.7
LINK      DIVR      HGP20     A407      1.000     142.14              125.3
LINK      DIVR      HGP21     A409C     1.000     119.51              265.7
LINK      DIVR      HGP21     A409B     1.000     119.51              265.7
LINK      DIVR      HGP21     A409A     1.000     119.51              265.7
LINK      DIVR      HGPSBV    U506      1.000     51.80               23.1
LINK      DIVR      U506      HARSBV    1.000     7.40                28.7
LINK      DIVR      WWP201    HNP201    1.000     1480.00             1.9
LINK      DIVR      WWP204    HNP204    1.000     518.00              0.6
LINK      DIVR      WWP205    HNP205    1.000     1480.00             2.9
LINK      DIVR      WWP207    HNP207    1.000     1480.00             1.9
LINK      DIVR      WWP209    HNP209    1.000     518.00              2.1
LINK      DIVR      WWP210    HNP210    1.000     1480.00             2.5
LINK      DIVR      WWP301    HNP301    1.000     1480.00             3.7
LINK      DIVR      WWP302    HNP302    1.000     1480.00             5.3
LINK      DIVR      WWP304    HNP304    1.000     518.00              1.3
LINK      DIVR      WWP401    HNP401    1.000     1480.00             8.1
LINK      DIVR      WWP403    HNP403    1.000     1480.00             3.3
LINK      DIVR      WWP405    HNP405    1.000     1480.00             4.8
LINK      DIVR      WWP406    HNP406    1.000     1480.00             3.9
LINK      DIVR      WWP407    HNP407    1.000     1480.00             3.2
LINK      DIVR      WWP410    HNP410    1.000     1480.00             6.1
LINK      DIVR      WWP501    HNP501    1.000     518.00              0.0
LINK      DIVR      WWP504    HNP504    1.000     1258.00             28.7
LINK      DIVR      WWP508    HNP508    1.000     1480.00             0.9
LINK      DIVR      WWP510    HNP510    1.000     1480.00             1.0
```

P.S. @whiteellie I don't think missing CN nodes/links would make any difference.

**Comment by msdogan** [comment]
I am also attaching new runs *pri
[test_dbg_round.zip](https://github.com/msdogan/HOBBEStoPRMcomparison/files/479111/test_dbg_round.zip)

**Comment by jrmerz** [comment]
All.  I started manually examining our current HOBBES v S09I05 timeseries DSS files and quickly came across this with node C32.

![screen shot 2016-09-19 at 8 54 18 am](https://cloud.githubusercontent.com/assets/1852393/18639213/d0e8445e-7e47-11e6-95b3-2c2871a4e60f.png)

These are the only records for C32 in each DSS file.  Obviously they are completely different.  While I don't have the access DB that generated S09I05, you can see [here](https://github.com/ucd-cws/calvin-network-data/blob/master/data/sacramento-river/central-basin-east/c32/inflows/default.csv) the DSS file is representing the correct values from HOBBES.  Another thing to note, HOBBES is defined as FLOW_LOC(KAF), local inflow.  While S09I05 is defined as FLOW_DIV which the manual defines as 'Flow diverted (in kaf) from this node. It is stored with pathname part B containing the "from" node and the "to" node identifiers separated by a "-" character.'  Not sure if that is playing a role or not.

@jdherman It will be a bit of work to have the pri parser to generate a new pri file.  But if you just want a rounded version of the HOBBES pri file, this can be accomplished with the current pri writer.   I just need to adjust the numeric values when printed.  Otherwise, I can create a writer from the parser if needed.

**Comment by jdherman** [comment]
@jrmerz ok it sounds like @msdogan is already doing an experiment with the PRI rounding, so don't worry about that for now.

Thanks for looking into the DSS files! It's good to know that something is substantially different, and we're not just crazy. I have no idea what this means or why it could be happening -- I'll have to defer to the experts here.

**Comment by msdogan** [comment]
@jrmerz these are two different output time-series. Let me try to explain it. FLOW_LOC(KAF) means only local flow (including rim inflow or gw inflow) into node C32. This is b_j parameter if you recall model formulation. We never postprocess FLOW_DIV(KAF) for nodes, we use it for links. But, I just took a look at output file, and it looks like FLOW_DIV(KAF) is total flow leaving a node. There is another parameter called FLOW_IN(KAF), which means total flow entering to a node, including FLOW_LOC. Hope this was not confusing.
@jdherman my rounded test run ended with a feasible solution. I will postprocess results and let you all know soon.

**Comment by jrmerz** [comment]
I think I follow the definitions (and sorry for my knowledge gap on this).  What file are you seeing  the FLOW_IN parameter for C32?  I'm guess what throws me is I only see 1 entry in both S09I05_TS.dss and HOBBES_TS.dss for node C32 and they contain different parameters (FLOW_LOC v FLOW_DIV) and values.  That is probably the base of my confusion.  Perhaps we can table this (my question) until the meeting.

**Comment by msdogan** [comment]
No worries @jrmerz this is our fault that we use the same definitions in many places and all mean different things. FLOW_LOC is used in both input and output and they are different. I am guessing you are looking at input DSS files (####TS.DSS and ####PD.DSS). I would compare results in output DSS file (####.DSS), which I couldn't upload here because of its size, but I can try to find a way to share if necessary. I can also further explain these definitions in input and output in tomorrow's meeting.

Edit: By reading your comment again @jrmerz of course you would compare input files in ####TS.DSS and ####PD.DSS. Not output my bad sorry. So, those FLOW_DIV files you see in input file are coming from previous run's feasible solution (initial solution). So, if there is anything with S09I04 in Part A in S09I05TS.DSS, please ignore those, since they are initial basic solutions from previous run.

**Comment by msdogan** [comment]
I am closing this issue. We already compared pumping operations and they are different. Follow up on https://github.com/msdogan/HOBBEStoPRMcomparison/issues/10
